local_backend: true

backend:
  name: github            # use local git backend for Sveltia/Decap with proxy
  repo: vinylen2/intric-support
  branch: main
  base_url: https://api.netlify.com
  site_id: 30dbaea2-b1e7-4ec1-9e3c-baae73c905e6

media_folder: "static/uploads"
public_folder: "/uploads"

# Reuse this enum for all three languages
# The value maps to the subfolder name
category_options: &category_options
  - { label: "Getting started",   value: "getting-started" }
  - { label: "Account & billing", value: "account-billing" }
  - { label: "Troubleshooting",   value: "troubleshooting" }

collections:
  # English content pages
  - name: "pages_en"
    label: "English › Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/en/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "content/en/about/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Docs Landing"
        name: "docs_landing"
        file: "content/en/docs/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Weight", name: "weight", widget: "number", value_type: "int", min: 0, required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "content/en/contact/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "english_docs_functionality"
    label: "English › Docs › Functionality"
    folder: "content/en/docs/Functionality"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}"
    fields: &docs_fields
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Weight", name: "weight", widget: "number", value_type: "int", min: 0, required: false }
      - { label: "Draft", name: "draft", widget: "boolean", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "english_docs_getting_started"
    label: "English › Docs › Getting Started"
    folder: "content/en/docs/getting-started"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}"
    fields: *docs_fields

  - name: "english_docs_guides"
    label: "English › Docs › Guides"
    folder: "content/en/docs/guides"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}"
    fields: *docs_fields

  - name: "english_docs_settings_admin"
    label: "English › Docs › Settings & Admin"
    folder: "content/en/docs/settings-and-admin"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}"
    fields: *docs_fields

  # Swedish content
  - name: "swedish_pages"
    label: "Swedish › Pages"
    files:
      - label: "Home (SV)"
        name: "home_sv"
        file: "content/sv/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Docs Landing (SV)"
        name: "docs_landing_sv"
        file: "content/sv/docs/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Weight", name: "weight", widget: "number", value_type: "int", min: 0, required: false }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "swedish_docs_functionality"
    label: "Swedish › Docs › Functionality"
    folder: "content/sv/docs/Functionality"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}"
    fields: *docs_fields

  - name: "swedish_docs_getting_started"
    label: "Swedish › Docs › Getting Started"
    folder: "content/sv/docs/getting-started"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}"
    fields: *docs_fields

  - name: "swedish_docs_guides"
    label: "Swedish › Docs › Guides"
    folder: "content/sv/docs/guides"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}"
    fields: *docs_fields

  - name: "swedish_docs_settings_admin"
    label: "Swedish › Docs › Settings & Admin"
    folder: "content/sv/docs/settings-and-admin"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}"
    fields: *docs_fields
